Front issues resolution
KIClubinfo/upont-v4 pull request #120
Opened 2022-09-22 15:08 UTC by sachabinder

- Photo/club photo front profile
- Order of buttons to change profile in personal profile page
- Post front : Display date of each post, Title of the post, placeholder on comment,  date under comment, usable button on comment author, add event button, like and comment zone.
- fix bug on comment delete button

2022-09-23 16:32 UTC, StephaneGrabsia approved these changes
CR ok, good job

2022-09-23 16:32 UTC, StephaneGrabsia commented on back/news/templates/news/event_detail.html
> +                    <div class="centered-div mt-2">
Don't you think we should indent this block for clarity purpose?

2022-09-25 12:31 UTC, LudoBike commented
# Post create/edit
It looks quite awful on my computer (cf screenshot). Space is missing under selection lists and the selection lists are wider than the other inputs. I also think it is strange that the description input is centered rather than left aligned.

![image](https://user-images.githubusercontent.com/14591631/192142693-f67645a1-21c8-40ff-89cc-d8fffd616c36.png)

# Posts
I remark that H1 in description are bigger than the title of the post but it is not necessarily an issue. 

However the name of the linked event is not written and I find that strange. Perhaps we can specify "Ce post est lié à l'évènement : [nom]" before the post title or between the title and the description. Otherwise it is still better than the old version.

![image](https://user-images.githubusercontent.com/14591631/192142942-cda69158-d163-41a8-a5ca-77ad17b8f216.png)

# Profile
It's great, perhaps we can just add a test to display the nickname only if it is different from the full name, otherwise the same info is written twice. 

![image](https://user-images.githubusercontent.com/14591631/192143292-ea726c42-6d97-4187-875a-e1e588a7896b.png)

And I find strange that the navbar highlight "Profil" rather than "Élèves" when we look at the profil of another user.

![image](https://user-images.githubusercontent.com/14591631/192143346-f84fd26d-b123-45d3-8aed-41d196d61345.png)

# Profile edit
Similarly to post edit, the selection list are wider than the other inputs.

![image](https://user-images.githubusercontent.com/14591631/192143424-07edd05b-3556-46fe-bb51-1d9011fa24c5.png)

2022-09-25 12:32 UTC, LudoBike reviewed
cf https://github.com/KIClubinfo/upont-v4/pull/120#issuecomment-1257183964

2022-10-02 21:36 UTC, TheoContentin reviewed
Agreeing with Stéphane, change are all ok to me, typo in CSS can be problematic

2022-10-06 10:59 UTC, sachabinder commented
Some other things ?

2022-10-12 11:21 UTC, LudoBike requested changes
Add name of related event in post card

2022-10-12 20:42 UTC, LudoBike approved these changes

2022-10-12 20:45 UTC, merged