Major review of the front of news app
KIClubinfo/upont-v4 pull request #71
Opened 2022-02-12 13:51 UTC by dadou15

2022-02-12 14:33 UTC, bastienlc requested changes

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/event_detail.html
> +                                            <a href="{% url 'news:post_edit' post.id %}?next=event_edit"><button class="button blue-button">Éditer</button></a>
```suggestion
                                            <a href="{% url 'news:post_edit' post.id %}"><button class="button blue-button">Éditer</button></a>
```

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/event_detail.html
> +                            <a href="{% url 'news:events' %}"><button class="button blue-button">Retour à l'index</button></a>
```suggestion
                            <a href="{% url 'news:events' %}"><button class="button blue-button">Retour à l'index</button></a>
                            {% if is_member %} <a href="{% url 'news:event_edit' event_id=event.id%}"><button class="button blue-button">Modifier</button></a>
                            {% endif %}
```

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/events.html
> +{% include "header.html" with title="Modifier l'évènement" %}
```suggestion
{% include "header.html" with title="Évènements" %}
```

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/shotguns.html
>              </div>
```suggestion
```

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/shotguns.html
> +
```suggestion
<div class="centered-div mt-2">
                {% if display_admin_button %}
                    <a href="{% url 'news:shotguns_admin' %}" style="text-decoration: none"><button class="button blue-button">Administration des shotguns</button></a>
                    <br>
                {% endif %}
                <a href="{% url 'news:new_shotgun' %}"><i class="fas fa-plus-circle fa-5x"></i></a>
            </div>
```
Quelque chose dans ce style pour mettre les boutons d'administration en bas.

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/shotguns_admin_detail.html
> +                        {% if shotgun.is_ended and shotgun.requires_motivation%}
```suggestion



                        {% if shotgun.is_ended and shotgun.requires_motivation%}
                            <div class="box small-box">
```

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/shotguns_admin_detail.html
> +                                </div>
```suggestion
                                </div>
                                </div>
```

2022-02-12 14:33 UTC, bastienlc commented on back/news/templates/news/shotguns_admin_detail.html
> +                    </div><!--End of Box-->
```suggestion
```

2022-02-12 15:16 UTC, dadou15 commented on back/news/templates/news/shotguns.html
>              </div>
Je suis plus d'avis de mettre le bouton d'administration tout en haut en évidence pour pas le chercher 2 heures si la page est pleine. Oublie pas que s'il a beaucoup de shotguns, il va être perdu tout en bas. Je vais trouver une meilleure solution.

2022-02-12 15:18 UTC, dadou15 commented on back/news/templates/news/shotguns_admin_detail.html
> +                        {% if shotgun.is_ended and shotgun.requires_motivation%}
C'est ça le problème de div vide si ca respecte pas une certaine condition c'est ca ?

2022-02-12 15:27 UTC, dadou15 commented on back/news/templates/news/shotguns_admin_detail.html
> +                                </div>
je comprend pas ça, est-ce que je l'ai résolu dans le dernier conflit ?

2022-02-13 01:37 UTC, bastienlc commented on back/news/templates/news/shotguns.html
>              </div>
Pour l'instant c'est mieux en effet mais on pourra limiter la hauteur de la page avec des boutons "charger plus" à l'avenir.

2022-02-14 11:04 UTC, bastienlc approved these changes

2022-02-15 11:24 UTC, merged