Added old members management functionnalities
KIClubinfo/upont-v4 pull request #77
Opened 2022-02-19 20:27 UTC by Louis-Bly

You need to make migrations before working on the branch

Front is suboptimal, I let David take care of it

2022-02-21 11:09 UTC, TB023 submitted a review, later dismissed

2022-03-01 15:07 UTC, bastienlc requested changes
The front needs to be fixed before merging.

2022-09-29 20:06 UTC, sachabinder commented
We maybe should add some toggles to display other promo (this allow to choose if we want to see or not) as [here](https://enpc.org/clubinfo/clubinfo.enpc.org/equipe.html)

2022-10-02 22:46 UTC, TheoContentin commented on back/social/templates/social/club_edit.html
> +                {% if all_active_club_memberships %}
There is a problem in the logic here for the edge case where there is no longer any active member the buttons wont show. A variable all_inactive_club_membership  would be better

2022-10-02 22:52 UTC, TheoContentin reviewed
CR ok, execpt for the template of club edit. Very good job

2022-10-12 21:13 UTC, LudoBike approved these changes

2022-10-12 21:31 UTC, sachabinder approved these changes

2022-10-12 21:31 UTC, merged